stages:
  ingest:
    cmd: python src/ingestion.py
    deps:
      - src/ingestion.py
    outs:
      - data/raw_data.csv

  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - src/preprocessing.py
      - data/raw_data.csv
    outs:
      - data/processed_data.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed_data.csv
    outs:
      - model.pkl